# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"wellcome": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://danph.github.io/ds4transport/"

git_url = "https://github.com/danph/ds4transport/tree/master/"

def custom_doc_links(name): return None
