# AUTOGENERATED! DO NOT EDIT! File to edit: 01_introduction.ipynb (unless otherwise specified).

__all__ = ['wellcome']

# Cell
def wellcome(name=''):
    return (f'Wellcome {name} to Data science for transport')